### ISSUE TITLE
Whats the difference between these two libraries

### ISSUE THREAD

**Issue by lholmquist** [aerogear/unifiedpush-admin-client#138]
Since i'm still part of the Aerogrear org i get notifcations, and a while back when this repo was created,  I wondered what the difference is between this library,  and the one that I had started here:  https://github.com/bucharest-gold/unifiedpush-admin-client

I also create a node module that does the registration also, which is here: https://github.com/bucharest-gold/unifiedpush-registration-client

Both repo's are not archived, since there wasn't much traction on them,  but just wanted to share

**Comment by ziccardi** [comment]
Hi @lholmquist !

The main differences are basically 2:
1. the new packages (both the [unifiedpush-admin-client](https://github.com/aerogear/unifiedpush-admin-client) and the [aerogear-push-js](https://github.com/aerogear/aerogear-push-js) are written from scratch using typescript instead of the plain javascript
2. the new packages, inside the `@aerogear` namespace are maintained by the aerogear unifiedpush team and, since we made some changes to the ups, we wrote them supporting the new syntax and the new features of the UPS Rest endpoints

Finally, the new and updated unifiedpush-admin-client library has been used as the core for the new [Admin UI](https://github.com/aerogear/unifiedpush-admin-ui) and the new [UPS CLI](https://github.com/aerogear/unifiedpush-cli)

Hope this answers to your question!
